[package]
name = "fractal_drum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
nalgebra = "0.32.2"
ndarray = "0.15.6"
plotters = "0.3.4"
timeit = "0.1.2"
